name: Scheduled Script Run

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour at the top of the hour
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    
    - name: Set up Python
      run: uv python install
    
    - name: Install dependencies
      run: uv sync
    
    - name: Run script
      run: uv run python main.py
      env:
        BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
