name: Scheduled Script Run

on:
  push:
  schedule:
    - cron: '31 */3 * * *'  # Run at 31 minutes past every 3 hours
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    
    - name: Install dependencies
      run: uv sync
    
    - name: Run script
      run: uv run python main.py
      env:
        BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
        X_BEARER_TOKEN: ${{ secrets.X_BEARER_TOKEN }}
        X_API_KEY: ${{ secrets.X_API_KEY }}
        X_API_KEY_SECRET: ${{ secrets.X_API_KEY_SECRET }}
        X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
        X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
    
    - name: Commit updated CSV
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add posted_reports.json
        git diff --staged --quiet || git commit -m "Update posted reports CSV [skip ci]"
        git push
